### ISSUE TITLE
[Client] No access to line numbers (high prio)

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#12]
Implement a checkbox to take codeline numbers in account when generating nodes.

**Comment by jeromecomte** [comment]
Implemented and committed to branch develop. Please test

**Comment by dcransac** [comment]
Seems to work as intended, but suspicious (negative) values found.

Also I need to have a test case where the same method branches into two different line numbers to be able to test this out properly. If you already commited a test case for that, please point it out, otherwise I'll implement one and commit it into the develop branch directly.

![image](https://cloud.githubusercontent.com/assets/5418782/14108081/e426cfaa-f5bb-11e5-9aac-9e8718cd0181.png)

**Comment by dcransac** [comment]
Just realized there was sort of an error message in the client's standard output (might be of use) :

line 1:0 no viable alternative at input '<EOF>'
OSQLToMongoQuery.g: node from line 0:0 no viable alternative at input ''

**Comment by jeromecomte** [comment]
-2 means: (Native Method)
-1 means: (Unknown Source)

As defined in java.lang.StackTraceElement:
    public String toString() {
        return getClassName() + "." + methodName +
            (isNativeMethod() ? "(Native Method)" :
             (fileName != null && lineNumber >= 0 ?
              "(" + fileName + ":" + lineNumber + ")" :
              (fileName != null ?  "("+fileName+")" : "(Unknown Source)")));
    }

I could use the same translation

**Comment by dcransac** [comment]
Sure, sounds good. A translation seems more intuitive for the end user, but
comes at a cost  (code maintenance). And we need to test this on an IBM
JVM. They might have a different translation scheme.

If IBM is different, then I suggest that we leave the value "as is" / "as
given". People can look it up, or we can document that case ourselves too.

**Comment by jeromecomte** [comment]
Could you please test it on IBM? If IBM is using the same translation sheme I would implement it.

**Comment by dcransac** [comment]
Tested on IBM J9 JDK on Windows. Works the same wait (at least for value -2). You can implement the translation if you want, but that's definitely a low prio thing.

**Comment by dcransac** [comment]
Actually I'm comfortable with no translation -> closing.
