### ISSUE TITLE
[Client] Hardcoded system path to tools.jar in client pom.xml

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#17]
Externalize JDK Path via variable or commit the "currently supported JDK Jar File itself"..?

**Comment by jeromecomte** [comment]
Fixed: 
Changed path in pom.xml: <systemPath>${java.home}/lib/tools.jar</systemPath>
To set java.home you could either set JAVA_HOME as environment variable or set it as property in settings.xml: 

<profiles>
  <profile>
    <id>default</id>
    <properties>
      <java.home>D:/Programs/jdk1.7.0_79</java.home>
    </properties>
  </profile>
</profiles>
<activeProfiles>
  <activeProfile>default</activeProfile>
</activeProfiles>

**Comment by dcransac** [comment]
For some reason, maven is resolving the variable as follows :
D:\Program Files\Java\jdk1.8.0_73\_jre_\lib\tools.jar

I don't know where he's getting that JRE path from. Any idea?

![image](https://cloud.githubusercontent.com/assets/5418782/14279200/348bfc98-fb2c-11e5-9c4a-a80f0ebcb1f9.png)

`<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository/>
  <interactiveMode/>
  <usePluginRegistry/>
  <offline/>
  <pluginGroups/>
  <servers/>
  <mirrors/>
  <proxies/>
  <profiles>
       <profile>
         <id>default</id>
         <properties>
           <java.home>D:\Program Files\Java\jdk1.8.0_73</java.home>
         </properties>
   </profile>
  </profiles>
  <activeProfiles/>
</settings>
`

![image](https://cloud.githubusercontent.com/assets/5418782/14279247/80c01b3a-fb2c-11e5-8321-cfac59f263f9.png)


![image](https://cloud.githubusercontent.com/assets/5418782/14279258/8e2eb4ca-fb2c-11e5-8acf-d33a6443f50e.png)

**Comment by jeromecomte** [comment]
It seems that maven adds the "/jre" automatically. I will change the pom.xml to take this into account. As a workaround you could try to remove the ENV Variable and maven will use the one defined in settings.xml

**Comment by dcransac** [comment]
What ENV variable?

**Comment by jeromecomte** [comment]
JAVA_HOME under "Variables système"

**Comment by dcransac** [comment]
Nope, that doesn't work. That's not where maven takes that value from.

`[ERROR] Failed to execute goal on project client: Could not resolve dependencies for project io.djigger:client:jar:1.4.1-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.7 at specified path D:\Program Files\Java\jdk1.8.0_73\jre\lib\tools.jar -> [Help 1]
`

**Comment by jeromecomte** [comment]
OK. Then I'll commit the following change:

		<dependency>
			<groupId>com.sun</groupId>
			<artifactId>tools</artifactId>
			<version>1.7</version>
			<scope>system</scope>
			<systemPath>${java.home}**/..**/lib/tools.jar</systemPath>
		</dependency>

**Comment by dcransac** [comment]
That means no process attach with IBM JDK, though correct? (just to clarify for documentation purposes)

**Comment by jeromecomte** [comment]
We should check if IBM distributes a special build with something equivalent to tools.jar... In any case it won't be possible to attach to an IBM JVM with an oracle tools.jar. It is even not possible to attach to an oracle JVM with a tools.jar from another JVM version.

**Comment by dcransac** [comment]
Yeah I assumed so.

So we'll take this as a temporary workaround (cause right now I can't build anymore because of this).

I just pulled but I don't see a commited change on the develop branch.

**Comment by dcransac** [comment]
Still doesn't work !? I don't understand why.

I'm just going to revert to the explicit path on my side for right now, so I can test the other issues. This was important, but not THAT important right now.



`		<dependency>
			<groupId>com.sun</groupId>
			<artifactId>tools</artifactId>
			<version>1.7</version>
			<scope>system</scope>
			<systemPath>${java.home}/../lib/tools.jar</systemPath>
		</dependency>`

**Comment by dcransac** [comment]
Must have been a local problem on my setup. Worked on a different setup.

WAI
