### ISSUE TITLE
[Collector/Client] Error handling : No or long timeout at jdbc level

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#20]
When accesing the DB (count() or sample retrieval), there should be a timout limit set at max 3 seconds, and a clear error message should be shown to the user

**Comment by jeromecomte** [comment]
Implemented and committed to develop. Timeout set at 30 seconds. 3s seems very restrictive when you're not having indexes on every attributes. This could be made configurable...

**Comment by dcransac** [comment]
Seems to work as intended, but personnally I would like to set this to max 10 sec. I don't really want to make a user wait 10+ seconds for an "estimate" of how long the actual routine will take.

If it's going to take longer than 3 seconds, then break (can we interrupt the query itself via mongo driver?!) and ask the user if he wants to retrieve the data at all (maybe he's querying too big a dataset on mistake, give him a chance to correct that mistake) ?!

**Comment by dcransac** [comment]
WAI
