### ISSUE TITLE
[Collector] TTL = 0 feature

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#21]
Some people need to disable the TTL function, because they're not using the collector for continuous monitoring but rather for temporary sessions, which they then want to keep archived in the DB. Setting the TTL duration to 0 in the config file could be interpreted as no TTL, meaning the data never expires. (maybe it actually works as intended already, I don't know how mongo interprets a TTL set to null? -> in that case, a simple test would be enough).

**Comment by jeromecomte** [comment]
Implemented and committed to develop

**Comment by dcransac** [comment]
Works as intended. Thanks.
