### ISSUE TITLE
[Client] Threads passing through a given node aren't displayed properly

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#22]
The red mark surrounding a thread's timeline doesn't seem to work when I click on a node in the tree after having filtered it (cosmetic filter, the second one), if I remember right.

This is annoying and needs to be fixed.

**Comment by jeromecomte** [comment]
I can't reproduce it:

![screenshot](https://cloud.githubusercontent.com/assets/17673828/14200070/ab1a4f14-f7e8-11e5-946d-901afa439269.png)

**Comment by dcransac** [comment]
I'll reopen when I can understand / specify / reproduce the problem easily.
