### ISSUE TITLE
[Client] [New functionality] Sampling-based branch analysis (min bound of method count) - High Prio

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#23]
We can provide a min method count automatically based on the observation of subsequent method calls and of call termination within a given method call (node).

The min bound count can be displayed on the same line as the rest of the numerical counters and percentages (following the symbolic name of the method) .

A complementary, specialized version of our block view could also be implemented to better visualize the resulting new data (see flame chats in the javascript world for instance).

**Comment by dcransac** [comment]
Prio ++ (need expressed from two separate active users)

**Comment by dcransac** [comment]
This is actually kind of redundant with Issue #16 .

There are two aspects here : 
1- Displaying methode count min bound in all trees
2- Adding a specialized "chronologic" view of the trees/nodes for a single thread selection (for chronological code analysis, which includes but isn't limited to some functional debugging purposes)

Aspect 2- relies on the implementation of aspect 1- and is therefore the top prio.

**Comment by dcransac** [comment]
For clarity, I suggest we track the implementation of the min bound mthod counts in this issue right here (issue #23 ). And the chronlogical view in issue #16  .

**Comment by jeromecomte** [comment]
Implemented in branch develop. Min count approximation is displayed in "<>" in the tree

**Comment by dcransac** [comment]
Perfect !! :+1: 

Absolutely tremendous feature

![image](https://cloud.githubusercontent.com/assets/5418782/14578939/dad00f44-0398-11e6-84e7-a3aaac0808e6.png)

**Comment by dcransac** [comment]
vraiment génial, t'assures.

au fait tu t'en es sorti pour l'histoire des dns exense?

**Comment by jeromecomte** [comment]
Ca va être super utile... A peine buildé j ai testé sur un problème syrius
à helsana que je voulais analyser avec l agent. Finalement j aurais pas
besoin de l agent non plus pour ce problème

Si t en as d autres comme celle la j implemente avec plaisir. A implementer
c est le genre de fonctions qui qui combinent après tout ce que recherche
un développeur

Comme tu l as probablement vu lors du checkout j en ai profité pour faire
un peu de refactoring dans les fonctions coeur. (C est a peu près la meme
sensation qu apres un bon nettoyage de printemps) du coup faudra être un
peu vigilent dans les tests a venir...

J ai aussi ajouter mon premier test junit. Si t as des cas de tests a
ajouter pour la feature tu peu y jeter un oeil. C est aussi l occasion de
voir si tout est implémenté comme tu le pensais.

Pour ce qui est de l affichage des mincounts je trouve que ca surcharge un
peu l arbre et surtout que les infos affichées a l utilisateur débutant
avec djigger ne sont plus du tout intuitives. Si t as une idée pour
améliorer ça...

Bon WE
Am 16.04.2016 6:06 Vorm. schrieb "Dorian Cransac" <notifications@github.com
