### ISSUE TITLE
[Client] The plus sign doesn't receive events in many cases (high prio)

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#26]
If the connection window :
- opens a failed session (see issue #24 )
- is shut explicitely via X by the user

then at least in these two cases, the plus sign can't produce/receive events anymore, which is annoying.

Also it's sort of redundant with the plus sign at the bottom (confusing).

![image](https://cloud.githubusercontent.com/assets/5418782/14231473/4645d560-f985-11e5-807e-7dc76d4bc426.png)

**Comment by jeromecomte** [comment]
Fix committed to develop. The "+" button in the tab list is quite intuitive if at least one tab is active, For the first connection I'm not sure if it's still the case. That's the reason why I let the initial button at the button. Should I still remove it?

**Comment by dcransac** [comment]
WAI.

It's fine, the redundancy is acceptable considering the potential benefit (ease of use for the user)
