### ISSUE TITLE
[Client] Unexpected Character exceptions are back (very high prio)

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#35]
Problem happens at least with "_" and "-"

![unexpectedchar](https://cloud.githubusercontent.com/assets/5418782/14240357/844a02f4-fa44-11e5-9c26-148689f2ea76.png)

**Comment by jeromecomte** [comment]
Fixed in branch develop

**Comment by dcransac** [comment]
Is there a reason as to why you only fixed "_" but not "-"..? Or did you just forget / not notice?

![image](https://cloud.githubusercontent.com/assets/5418782/14246396/1d46e34c-fa67-11e5-8c41-5da42a413525.png)

**Comment by jeromecomte** [comment]
No reason. I didn't notice. I'll add it.

**Comment by jeromecomte** [comment]
'-' added.

**Comment by dcransac** [comment]
Please take care of "<" and ">" as well. Very important for constructors.

**Comment by jeromecomte** [comment]
done

**Comment by dcransac** [comment]
WAI
