### ISSUE TITLE
No more standard & error output redirects (logging) - high prio

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#58]
Remove the stdout and stderr redirects in start scripts. Let the process write on these outputs and simply manage log files properly in a log folder via logging api.

**Comment by jeromecomte** [comment]
The start-scripts can be found under: /distribution/template/bin.

**Comment by dcransac** [comment]
There's still some sort of dupplicate between the "current output file", and the "redirect file" from the script.

I think we just need to eliminate that part :
 > ../log/client_%mydate%.stdout 2>&1

and let ouput into stdout.

And then just have a Rolling policy in place for the appender's file.

**Comment by jeromecomte** [comment]
Implemented in branch develop
