### ISSUE TITLE
[Client] [Store] Welcome message when successful connection + Default filter text  - high prio

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#59]
- let the user know that the store connection was successful (people seem to think it failed even though it worked)
- invite the user to enter a store filter and hit RETURN in the store filter to load samples
- add the default gray text like in the other filter input boxes: "Store filter (and, or and not operators supported)"

**Comment by jeromecomte** [comment]
Implemented. Please review/update the welcome message in MainFrame.displayWelcomeDialog()

**Comment by dcransac** [comment]
slight typo: "... press enter TO retrieve your data", but otherwise it's great.

BTW, dunno if I should open another issue for this but, when I enter a custom time range, I have to set the focus on the primary Store Filter to search otherwise the search fails (if I hit return from the date fields), it's kind of annoying and might lead again to people thinking the store doesn't work properly.
