### ISSUE TITLE
[Collector] NPE & failed sampler initialization upon initial connection refused

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#6]
Fix sampler initialization when some of the remote JVM's aren't initially reachable. This leads to NPE's and weird failed collector starts.

Seek @bug mentions in the collector classes (this is documented as commentar in certain parts of the code).

**Comment by jeromecomte** [comment]
Fixed and committed to branch develop. Please test

**Comment by dcransac** [comment]
Works as intended.
