### ISSUE TITLE
[Client] Allow switching between Thread name and Thread ID in client

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#66]
dynamic or incrementally named threads lead to visualization issues in the client (for instance certain timers just keep incrementing a number that is then used in the naming), especially in Store mode when sampling slowly and analyzing a long period of time.

I suggest allowing the user to choose between using thread names or thread ids.

**Comment by jeromecomte** [comment]
Threads are already grouped by thread id in the thread selection panel. The
issue you re describing is caused by applications that permanently create
new threads...
Am 12.05.2016 3:27 Nachm. schrieb "Dorian Cransac" <notifications@github.com

**Comment by dcransac** [comment]
So that means the Java Thread Id is also incremented continuously? Damn it.

Alright then I guess the only option we have is "paging" the thread timeline view when more than X threads are loaded and add << >> page iterators...

**Comment by jeromecomte** [comment]
Yes. I ve implemented a thread filter in the branch develop. The annoying
thread could also be filtered out.
Am 12.05.2016 5:31 Nachm. schrieb "Dorian Cransac" <notifications@github.com

**Comment by dcransac** [comment]
Yeah I guess filtering is enough actually. I just wanted to address the cases where way too many threads are loaded "right from the beginning" (i.e I open a store session and the first search I do loads 10 000 different threads), before I get any chance to filter anything.

In some of my tests, that kind of scenario bugs out the client or I just couldn't scroll at all because the scrolling bar functionality in Swing was miserable.

I'll try to work on a couple of use cases to see if pagination is actually needed or not.

**Comment by jeromecomte** [comment]
There s a "known" bug in the update of the scroller that can be
workarounded by resizing the split panel. Please tell me if this also works
for you and i would increase the priority of the fix.
Am 12.05.2016 5:42 Nachm. schrieb "Dorian Cransac" <notifications@github.com

**Comment by dcransac** [comment]
Can't seem to reproduce the problem. Let's just go with the filter if we even have time (and reopen the issue later). Otherwise the main workaround will just be "zooming" into a smaller time window for right now.
