### ISSUE TITLE
[Client][SavedSession] Saved session is broken - Very high prio !

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#69]
Trees from 1.4.2 won't load anymore.

**Comment by dcransac** [comment]
Actually, 1.5.1 trees don't load either.

**Comment by jeromecomte** [comment]
Unable to reproduce in branch develop.

**Comment by dcransac** [comment]
There are a couple of different errors (StreamCorruptedException and InvalidClassException).

I don't understand why the problem can't be reproduced on your side since the problem is not platform-specific (I'm getting it on both windows and mac), and regardless of the files I'm loading (old saved sessions, fresh JMX exports, fresh Store exports).

Should I send you a sample file by email or just debugg these myself (I'm suspecting they have to do with recent changes done to the object model though)?

Error while reading session from file C:\Users\c1d\Desktop\test_session.djigger
java.io.StreamCorruptedException: invalid stream header: 3C6C6973
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804) ~[na:1.7.0_71]
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299) ~[na:1.7.0_71]
	at io.djigger.ui.model.SessionExport.normalRead(SessionExport.java:109) [classes/:na]
	at io.djigger.ui.model.SessionExport.read(SessionExport.java:103) [classes/:na]
	at io.djigger.ui.Session$2.run(Session.java:189) [classes/:na]
	at io.djigger.ui.common.MonitoredExecution$ProgressRunnable.run(MonitoredExecution.java:149) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Error while opening session from file C:\Users\c1d\Desktop\test_session.djigger
java.lang.NullPointerException: null
	at io.djigger.ui.Session$2.run(Session.java:190) ~[classes/:na]
	at io.djigger.ui.common.MonitoredExecution$ProgressRunnable.run(MonitoredExecution.java:149) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]

**Comment by jeromecomte** [comment]
Sessions from 1.4.2 cannot be read in 1.5.1 as the data model changed. That's the reason of the exception you've reported. If we want to support backward compatibility we should implement a "neutral" export format. For backward compatibility between 1.4.2 and 1.5.1 it's already too late. We could support it for the next releases... 

You've written a second comment "Actually, 1.5.1 trees don't load either." => this is the issue that I cannot reproduce

**Comment by dcransac** [comment]
Git Pull -> Parent build -> target archive unzipped -> client start -> JMX connection mode -> Sampling on a remote JVM for 10 seconds -> Export Session as File -> New Session -> Saved Session -> NullPointerException


Error while reading session from file C:\Users\c1d\Desktop\test_session.djigger
java.io.StreamCorruptedException: invalid stream header: 3C6C6973
        at java.io.ObjectInputStream.readStreamHeader(Unknown Source) ~[na:1.8.0_74]
        at java.io.ObjectInputStream.<init>(Unknown Source) ~[na:1.8.0_74]
        at io.djigger.ui.model.SessionExport.normalRead(SessionExport.java:109) [client-ui-1.5.1.jar:na]
        at io.djigger.ui.model.SessionExport.read(SessionExport.java:103) [client-ui-1.5.1.jar:na]
        at io.djigger.ui.Session$2.run(Session.java:181) [client-ui-1.5.1.jar:na]
        at io.djigger.ui.common.MonitoredExecution$ProgressRunnable.run(MonitoredExecution.java:154) [client-ui-1.5.1.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]
Error while running monitored execution
java.lang.NullPointerException: null
        at io.djigger.ui.Session$2.run(Session.java:182) ~[client-ui-1.5.1.jar:na]
        at io.djigger.ui.common.MonitoredExecution$ProgressRunnable.run(MonitoredExecution.java:154) ~[client-ui-1.5.1.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]

**Comment by dcransac** [comment]
Ok now I get it. Looks like the button - function mappings have changed..?

It seems the Session Export and hence now Saved Session only loads the session's configuration but not the data anymore.

Proper Tree Export is now done only inside the tree pane, but... how to you _load_ binary data files now then, if Saved Session only understands config? Saved Session as an import of data files definitely doesn't work.

**Comment by dcransac** [comment]
Just tested in 1.4.2 :

the reimport of a binary data file via "Saved Session" works. In 1.5.1 not anymore.

You probably tested session config import but not session data import. Can you please confirm?

**Comment by jeromecomte** [comment]
Nothing changed. The save button in the middle only saves the configuration
and not the data. I known it s confusing and should be optimized... This
would be a CR for the next release...
Am 02.06.2016 5:33 Nachm. schrieb "Dorian Cransac" <notifications@github.com

**Comment by dcransac** [comment]
I realize this now (probably forgot when initially started testing again), but it doesn't change anything : in my environment : the **data** exports won't load in 1.5.1

**Comment by dcransac** [comment]
I did a series of things to ensure I was executing a correct workflow (erased all files, wrote into clean files, and also restarted my VM cause I couldn't rebuild properly anymore) and now the files are opening correctly again...

I believe this might be due to me overriding the same file over and over ("test.djigger") or not being able to produce an up-to-date archive.

Sorry about that.

**Comment by dcransac** [comment]
Ahhh I think I realize what's going on!

The problem is actually a combination of data and conf files !

**If** I :
- export a data file
- import it
- export it as a configuration file

then the configuration file won't load.

I'm not sure this is the exact scenario that I did or something similar, and it's a tricky and silly case, but that **does** lead to a NPE and could explain my problem.

**Comment by jeromecomte** [comment]
I can't even reproduce this. The following example is working in my case. The NPE means that the binary couldn't be parsed (an explicit error msg would be better...). Are you sure, that your C:\Users\c1d\Desktop\intg.djigger isn' corrupt?

```
<list>
  <io.djigger.ui.SessionConfiguration>
    <name>test.djigger</name>
    <type>AGENT_CAPTURE</type>
    <parameters>
      <entry>
      <io.djigger.ui.SessionConfiguration_-SessionParameter>FILE</io.djigger.ui.SessionConfiguration_-SessionParameter>
        <string>D:\Temp\test.djigger</string>
      </entry>
    </parameters>
  </io.djigger.ui.SessionConfiguration>
</list>
```

**Comment by dcransac** [comment]
I had just produced the file, 100% clean, from the client, so yeah.

Anyways I'm closing this for right now until we get a better idea of what the problem is/might be then.

I'm also clearing the milestone.
