### ISSUE TITLE
Collector for jstack files

### ISSUE THREAD

**Issue by david-stephan** [denkbar/djigger#70]
In context where jstack is the only way to get thread dumps, it would good to be able to collect the dumps in realtime and store them like with the other modes (agent, jmx...)

**Comment by jeromecomte** [comment]
Implemented in branch develop. Will be released with 1.5.1
The "tail -f" feature will be available in both realtime (client) and collector modus.

To use it with the collector you'll have to define the connection in "Connections.xml" the following way:

<Group>
	<attributes />
	<groups>
		<Connection connectionClass="io.djigger.client.JstackLogTailFacade">
			<samplingParameters samplingRate="1000" />
			<connectionProperties>
				<property name="file" value="D:\Temp\jstack.log" />
			</connectionProperties>
			<attributes>
				<entry>
					<string>foo</string>
					<string>bar</string>
				</entry>
			</attributes>
			<subscriptions>
			</subscriptions>
		</Connection>
	</groups>
</Group>
