### ISSUE TITLE
Import legend for block view

### ISSUE THREAD

**Issue by david-stephan** [denkbar/djigger#71]
Custom legend used and defined in block view can be exported easily.  Unfortunately, an exported legend can't be imported in a new session.

**Comment by jeromecomte** [comment]
Currently (r1.4.x) an exported legend can be imported using the following Program-Argument -colorer="D:\Temp\legend.xml" (secret feature ;) )

As of 1.5.1 this will be possible in the GUI (new button)

Thanks for the defect.
