### ISSUE TITLE
Collector for process attach connections

### ISSUE THREAD

**Issue by david-stephan** [denkbar/djigger#72]
Enable collection for connections done with process attach as JMX can't be enabled in every context.

**Comment by jeromecomte** [comment]
Implemented in branch develop. Will be released with 1.5.1.

To enable process attach collection you'll have to run a collector instance on the same machine of the process. Here a sample "Collector.xml" to active process attach:

`<Group>
	<attributes />
	<groups>
		<Connection connectionClass="io.djigger.client.ProcessAttachFacade">
			<samplingParameters samplingRate="1000" />
			<connectionProperties>
				<property name="processNamePattern" value="<regex pattern>" />
			</connectionProperties>
			<attributes>
				<entry>
					<string>foo</string>
					<string>bar</string>
				</entry>
			</attributes>
			<subscriptions>
			</subscriptions>
		</Connection>
	</groups>
</Group>`
