### ISSUE TITLE
[Client][JMX] Failed to parse at line 1due to no viable alternative at input '<EOF>'

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#73]
While just hitting the refresh button during a JMX sampling session :

![image](https://cloud.githubusercontent.com/assets/5418782/15751334/0c10eada-28ea-11e6-9d3d-78355911295c.png)

**Comment by dcransac** [comment]
Problem appeared a couple of times again, but after sampling several times and for several hours today, I was unable to reproduce it.

It could be related to the antlr 4 change, for example I see an issue with a similar message there:https://github.com/antlr/antlr4/issues/606

Maybe we could just test and make sure that a full stacktrace is logged (i.e we don't "just" display a popup message) when antlr throws an exception. That way we would have a better chance to diagnose the issue.

I'm not sure if we want to release 1.5.1 with this (and add a minor fix later if it turns out people run into this problem a lot)..?

**Comment by dcransac** [comment]
I'm pretty sure it has to do with an incorrect expression I entered or an expression that use to work and is not supported in antl4 anymore.

I can reproduce the problem now but only if I enter an incorrect expression like for example just "and". I believe the old behavior was to just show an empty tree instead of displaying an error message. 

So yeah : stacktrace + potentially a "clearer" error message (like "incorrect query") or revert to just an empty tree..?

**Comment by dcransac** [comment]
Suggestion for the future : maybe we could start using MDC's so that within the context of a query, we can naturally or "elegantly" log some of the context like the actualy query itself. That way we'll make the bug reporting and the debugging easier.

**Comment by jeromecomte** [comment]
Clearer error message implemented and commited.
MDC would be a good idea. We should create a separate CR for that.
Am 07.06.2016 1:41 Nachm. schrieb "Dorian Cransac" <notifications@github.com
