### ISSUE TITLE
Missing stacktraces in collector DB

### ISSUE THREAD

**Issue by mhaenggi** [denkbar/djigger#78]
Lately I had two cases where I couldn’t find stack traces in the collector DB. 

Ex1: With a core dump on a looping machine you could see one 3 Weblogic threads looping in HashMap.getEntry() for ever. But there was nothing to see in the Djigger data we collected.

Ex2: Again on Weblogic. ExecutThread “12” is busy working on collecting data for a search result. Dynatrace PurePath timed out after 10 minutes (the whole thing run over 2 days). But in Djigger again there was nothing to find about this business logic. 

As you can see in ex. 2 the thread name is not exactly the same ([ACTIVE] vs. [STANDBY]). But I’m sure it’s the same thread. 

![dynatrace](https://cloud.githubusercontent.com/assets/18693881/16941935/7057c3a6-4d93-11e6-848b-af1a0a1a7b2f.png)
![djigger](https://cloud.githubusercontent.com/assets/18693881/16941844/ecce4b9a-4d92-11e6-9d7e-747272040635.png)

**Comment by mhaenggi** [comment]
Got a 3rd example. We have the looping ExecuteThread ‘1’. I collected 5min directly with the djigger client over JMX and the same 5 min from the collector DB. 

via JMX:
![ex3_djigger_client](https://cloud.githubusercontent.com/assets/18693881/16945012/8baf35ca-4da3-11e6-8b6c-7cc4aa3c1260.png)

via collector DB:
![ex3_djigger_collector](https://cloud.githubusercontent.com/assets/18693881/16945061/d19f5a60-4da3-11e6-8894-61a3b01ae91a.png)

Both sessions are stored in the ZIP:
[ex3_djigger_sessions.zip](https://github.com/denkbar/djigger/files/371089/ex3_djigger_sessions.zip)

**Comment by jeromecomte** [comment]
Hi Michel,

I looked at the session you've exported. The data seem to come from the same VM (RMI Tcp Thread listening on the same host) but the timeframe of the collection seems to be different: all the threads named "Timer-*" have totally different counts. Based on the Thread-Counts the data of the session "ex3_djigger_collector.djigger" appear to be much older.  Could you please check the clock of your collector?

**Comment by mhaenggi** [comment]
The clock is fine. But we run two Djigger Collectors on the same server. One for PROD and one for PrePROD. The MongoDBs are listening on port 27017 (PrePROD) and 27018 (PROD). 
If I make connection to these ports with the client and query with „host=XYZ“ then just on one connection should return a result. But with host from PROD I get no results on both connections. With a host from PrePROD I get results on both.

I guess the client sessions to the store do not uses the port information for connection. But uses the default port 27017 for mongoDB.

**Comment by dcransac** [comment]
I thought I had fixed that a while back. What version of the client are you using? Can you make sure you're using 1.5.1?

**Comment by jeromecomte** [comment]
I confirm. This has been fixed with the following commit and should be therefore working as of 1.5.1: 
commit 6e4eb229a231845d2778ece2beab7dacbbd93fb1
Author: dcransac <dcransac@denkbar.io> 2016-06-09 16:17:56
Committer: dcransac <dcransac@denkbar.io> 2016-06-09 16:17:56

**Comment by mhaenggi** [comment]
Hmm, it looks like we still working with the early adaptor beta 1.5.1 version. I'll check that!

**Comment by mhaenggi** [comment]
Perfect :+1: 
I replaced the jars with the public version 1.5.1. and now I see the right traces.
thanks a lot, issue can be closed
