### ISSUE TITLE
[Client] Min count bound updates while sampler is turned off - High Priority

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#81]
Since the introduction of sampling-interval-based time estimates, it seems that min bound counts keep updating despite turning off the sampler. See image below.

![image](https://cloud.githubusercontent.com/assets/5418782/20524502/12a0e8ec-b0bb-11e6-9320-c979a43fd7e6.png)

**Comment by jeromecomte** [comment]
Fixed in branch develop

**Comment by dcransac** [comment]
Works as intended
