### ISSUE TITLE
[Client] Filename extensions 

### ISSUE THREAD

**Issue by clangguth** [denkbar/djigger#98]
Hi folks,

the client offers the option to save/load connections and sessions. Currently, the load and save dialogs don't place any filters on the file names, which IMO is suboptimal.

I suggest to define some sort of standard extension for these files, which would make it easier to use the save and load features. I'm willing to implement this, but before I do, we should find some sensible extension names :-)

The connection files are in fact xml files, and the sessions are binary data. So one option would be to simply use ".xml" for the former, and ".bin" for the latter. 

Another option (which I think makes more sense) would be to define proprietary ones, like ".djc" and ".djs", the question is simply what the extensions should be.

Of course, the dialogs would also still allow to override the filter and select "all files `(*.*)"` (just like all other applications do).

What do you guys think about this? And if you agree that this makes sense, what extensions would you suggest/prefer?

**Comment by dcransac** [comment]
Hello,

This is a good idea. I think just differentiating the different file types and setting the extension automatically would already go a long way as far as improving usability and helping with archiving.

While mainstream extensions such as .xml and .bin increase technical clarity and might make it more inviting to the user to manually open and edit the files manually (when they're editable), using custom extensions does have the advantage of potentially facilitating the loading workflow using native file extension handlers, especially in windows environments. As you mentioned it would also make the default filter more restrictive and therefore, potentially more accurate in certain search scenarios.

It's a relatively minor trade-off though, so I would totally leave the decision up to the person who bothers implementing the functionality.

**Comment by clangguth** [comment]
Well, since the person who'd implement it would probably be me :-) -- my personal choice would be ".djc" and ".djs", for the reasons mentioned above. However, I didn't want to step on project maintainers' toes...

So... I'll take your comment as a "fine with the suggested custom extensions" stance, right?

Then let's see if Jerome or anybody else has an opinion on this, and if there are no objections within a week or so, I'll go and implement it the way I suggested.

**Comment by dcransac** [comment]
I'm sure Jerome will be fine either way, go ahead ;)

**Comment by clangguth** [comment]
Closed with #100
